### ISSUE TITLE
ObjectMapper 兼容jsr310

### ISSUE THREAD

**Issue by chaomings** [lychs1998/CatMock#1]
![image](https://user-images.githubusercontent.com/25077986/88451758-ebcbcf00-ce8b-11ea-9537-e6001df743c3.png)

可以配置ObjectMapper ，让使用者可以使用`objectMapper.registerModule()`或者`objectMapper.configure()`过的对象,使支持各种情况。

**Comment by keleus** [comment]
感谢你的建议，我在1.2.1版本中提供了getMapper方法获取内部的Mapper对象，后续会新增构造方法以方便在初始化时就传入自定义的Mapper。

相关提交：commit 25ceae7fc6b274da1032d9a6f60294c31558318e

**Comment by keleus** [comment]
1.2.2版本中新增CatMock构造方法与getMapper方法用于传入与获取内置ObjectMapper对象。
